version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend
    ports:
      - '5252:5252'

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend
    ports:
      - '9000:9000'
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end

